create table Person(
	id int generated by default as identity primary key, 
	name varchar not null, 
	age int check (age > 0), 
	email varchar unique);

select * from person;

drop table person ;


insert into person (name, age, email) values('Jel', 62, 'jel@mail.ru');